```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Imports 
# library(spomic)
devtools::load_all("/Users/jacobchang/Lab/spomic")
library(beepr)
library(spatstat)
library(dplyr)
library(tidyr)
library(purrr)
library(pbmcapply)
library(metafor)
# 
# source("/Users/jacobchang/Lab/metadisco_paper/analysis/simulation/simulation_plotting_helpers.R")
# source("/Users/jacobchang/Lab/metadisco_paper/analysis/plotting_utils.R")

```

```{r}
# SIMULATION PARAMETERS 
N_SIM <- 100
WINDOW_SIZE <- 2000
R <- 200

BASE_DIR <- "/Users/jacobchang/Lab/checkmate_paper"
```

```{r}
intra_sample_n = 10
parent_lambda0 = 0.00001
offspring_n0 = 3
offspring_dispersion0 = 100

intra_sample_simulation <- function(intra_sample_n, 
                                    parent_lambda0, 
                                    offspring_n0, 
                                    offspring_dispersion0, 
                                    patient = "", 
                                    window_size = WINDOW_SIZE, 
                                    plot = FALSE) {
  intra_sample_results_list <- list()
  for(n in 1:intra_sample_n) {
    parent_lambda <- parent_lambda0 + runif(1, 0, 1/(window_size * window_size))
    offspring_n <- rpois(n = 1, offspring_n0) + 1
    offspring_dispersion <- abs(offspring_dispersion0 + rnorm(1, 0, 2))
      
    parents <- rpoispp(lambda = parent_lambda, win = square(window_size))
    # plot(parents)  
    offspring_x <- numeric()
    offspring_y <- numeric()
      
    if (parents$n > 0) {
      num_offspring <- rpois(parents$n, offspring_n) + 1
      new_x <- rnorm(sum(num_offspring), 
                     mean = rep(parents$x, num_offspring), 
                     sd = offspring_dispersion)
      new_y <- rnorm(sum(num_offspring), 
                     mean = rep(parents$y, num_offspring), 
                     sd = offspring_dispersion)
        
      valid_idx <- (new_x >= 0) & (new_x <= window_size) & (new_y >= 0) & (new_y <= window_size)
      offspring_x <- new_x[valid_idx]
      offspring_y <- new_y[valid_idx]
      }
      
    parent_ppp <- ppp(parents$x, parents$y, window = square(window_size), marks = rep("A", parents$n))
    offspring_ppp <- ppp(offspring_x, offspring_y, window = square(window_size), marks = rep("B", length(offspring_x)))
    marked_process <- superimpose(parent_ppp, offspring_ppp)
    marks(marked_process) <- as.factor(marks(marked_process))
    
    # if(plot) plot(marked_process, cols = c("red", "blue"))
    spomic <- create_spomic(ppp_to_df(marked_process, sample_name = ""))
    plot_spomic(spomic) |> print()
    spomic <- set_spomic_hyperparameters(spomic = spomic, 
                                         colocalization_type = "Lcross", 
                                         fixed_distance = FALSE, 
                                         r = R)
    spomic <- get_spatial_stats(spomic)
    # get_spatial_summary(spomic)
    if(plot) plot_spomic(spomic)
    intra_sample_results_list[[n]] <- get_spatial_summary(spomic) |> 
      mutate(patient = patient, 
             intra_sample = n)
    }
  return(bind_rows(intra_sample_results_list))
  }

# Outer loop for the simulation... 
set.seed(123)
inter_sample_simulation <- function(intra_sample_n) {
parent_lambda0 = 0.00001 + runif(1, 0, 0.0001)
offspring_n0 = 3 + rnbinom(1, size=10, mu=2)
offspring_dispersion0 = 100 + rnorm(1, mean=0, sd = 25)
  # parent_lambda0 <- rbeta(1, 2, 2) / WINDOW_SIZE
  # offspring_n0 <- rnbinom(1, size = 10, mu = 5) + 1
  # offspring_dispersion0 <- abs(rnorm(1, 0, 5))
  # 
  library(pbapply)
set.seed(123)
results_list <- pblapply(1:N_SIM, function(i) {
  intra_sample_simulation(
    intra_sample_n = intra_sample_n,
    parent_lambda0 = parent_lambda0,
    offspring_n0 = offspring_n0,
    offspring_dispersion0 = offspring_dispersion0,
    patient = i
  )
})

saveRDS(results_list, "cluster_process_list.rds")
  
  # results_list <- pblapply(1:N_SIM, 
  #                          function(i) intra_sample_simulation(
  #   intra_sample_n = intra_sample_n,
  #   parent_lambda0 = parent_lambda0,
  #   offspring_n0 = offspring_n0,
  #   offspring_dispersion0 = offspring_dispersion0,
  #   patient = i
  # ), 
  #                          mc.cores = detectCores() - 2)
  
  return(dplyr::bind_rows(results_list))
}
```

```{r}
# cluster_process_simulation <- inter_sample_simulation(intra_sample_n=100)
# saveRDS(cluster_process_simulation, file.path(BASE_DIR, "output/simulation/spatial_cox_process", "cluster_process_simulation.rds"))
```

```{r}
foo <- readRDS(file.path(BASE_DIR, "output/simulation/spatial_cox_process", "cluster_process_simulation.rds"))
```


```{r}
# head(foo)

foo = bind_rows(results_list)
intermediate_level <- foo |> group_by(patient, i_j) |> summarise(patient_mean = mean(colocalization_stat), 
                                                                 patient_sigma2 = var(colocalization_stat))

# intermediate_level <- foo |> group_by(patient, i_j) |> summarise(patient_mean = mean(kcross), 
#                                                                  patient_sigma2 = var(kcross))
total_level <- intermediate_level |>
  group_by(i_j) |> 
  summarise(mu = mean(patient_mean), 
            tau2 = var(patient_mean))


# total_level2 <- foo |> group_by(i_j) |> summarise(mu = mean(kcross), 
#                                                   tau2 = var(kcross))
total_level2 <- foo |> group_by(i_j) |> summarise(mu = mean(colocalization_stat), 
                                                  tau2 = var(colocalization_stat))

total_level
total_level2
```

```{r}

get_rmse <- function(truth, estimates) {
  return(sqrt(sum((estimates-truth)^2) / length(estimates)))
}


# foo <- readRDS("~/Lab/metadisco_paper/analysis/simulation/spatial_cox_process/test2_simulation_gt.rds")
num_studies <- 100
intra_sample_n <- 100
# Outer loop (number of studies)

naive_mu_rmse <- c()
naive_tau2_rmse <- c()

estimate_mu_rmse <- c()
estimate_tau2_rmse <- c()
for(j in 1:num_studies) {
  # Inner loop (intra-sample n)
  foo2 <- foo |> filter(patient <= j, i_j == "A_B")
  mu_estimate <- c()
  tau2_estimate <- c()
  
  naive_mu_estimate <- c()
  naive_tau2_estimate <- c()
  for(k in 1:intra_sample_n) {
    foo3 <- foo2 |> filter(intra_sample == k)
    model <- metafor::rma.uni(yi = foo3$kcross, vi = foo3$kcross_var, method = "SJ")
    mu_estimate[k] <- coef(summary(model))$estimate
    tau2_estimate[k] <- summary(model)$tau2
    naive_mu_estimate[k] <- mean(foo3$kcross)
    naive_tau2_estimate[k] <- var(foo3$kcross)
  }
  
  mu <- mean(foo2$kcross)
  tau2 <- var(foo2$kcross) # TODO: need to decide if this is the correct way to calculate tau2.... other way is to take variance of each patient's mean kcross....
  theta <- foo2 |> group_by(patient) |> summarise(theta = mean(kcross)) |> ungroup()
  tau2 <- var(theta$theta)
  
  naive_mu_rmse[j] <- get_rmse(truth = mu, estimates = naive_mu_estimate)
  estimate_mu_rmse[j] <- get_rmse(truth = mu, estimates = mu_estimate)
  
  naive_tau2_rmse[j] <- get_rmse(truth = tau2, estimates = naive_tau2_estimate)
  estimate_tau2_rmse[j] <- get_rmse(truth = tau2, estimates = tau2_estimate)
}

rmse_df <- data.frame(num_studies = 1:num_studies, 
                      naive_mu_rmse = naive_mu_rmse, 
                      estimate_mu_rmse = estimate_mu_rmse, 
                      naive_tau2_rmse = naive_tau2_rmse, 
                      estimate_tau2_rmse = estimate_tau2_rmse)

mu_rmse_long <- rmse_df |> dplyr::select(num_studies, naive_mu_rmse, estimate_mu_rmse) |> 
  pivot_longer(cols = -num_studies, names_to = "method", values_to = "rmse")

library(ggplot2)
library(ggpubr)
plot_mu <- ggplot(mu_rmse_long, aes(x = num_studies, y = rmse, color = method)) +
  geom_line(linewidth = 0.5) +
  geom_point(size = 1) +
  labs(title = bquote("RMSE of " * mu * " estimates for (A,B)"),
       x = "Number of Studies",
       y = "RMSE",
       color = "Method") +
      scale_color_manual(
    values = c(
      "estimate_mu_rmse" = "#1f77b4",
      "naive_mu_rmse" = "#ff7f0e"
    ),
    labels = c(
      "estimate_mu_rmse" = "Meta-DiSCO estimate",
      "naive_mu_rmse" = "Naive estimate"
    )) + 
  theme_minimal() + 
  theme_pubr()+ 
  theme_publication_text()

tau2_rmse_long <- rmse_df %>%
  dplyr::select(num_studies, naive_tau2_rmse, estimate_tau2_rmse) %>%
  pivot_longer(cols = -num_studies, names_to = "method", values_to = "rmse")

plot_tau2 <- ggplot(tau2_rmse_long, aes(x = num_studies, y = rmse, color = method)) +
  geom_line(size = 0.5) +
  geom_point(size = 1) +
  labs(title = expression("RMSE of " * tau^2 * " estimates for (A,B)"),
       x = "Number of Studies",
       y = "RMSE",
       color = "Method") +
    scale_color_manual(
    values = c(
      "estimate_tau2_rmse" = "#1f77b4",
      "naive_tau2_rmse" = "#ff7f0e"
    ),
    labels = c(
      "estimate_tau2_rmse" = "Meta-DiSCO estimate",
      "naive_tau2_rmse" = "Naive estimate"
    )) + 
  theme_minimal() + 
  theme_pubr() + 
  theme_publication_text()
  

plot_tau <- ggplot(tau2_rmse_long, aes(x = num_studies, y = sqrt(rmse), color = method)) +
  geom_line(size = 0.5) +
  geom_point(size = 1) +
  labs(title = expression("RMSE of " * tau * " estimates for (A,B)"),
       x = "Number of Studies",
       y = "RMSE",
       color = "Method") +
  scale_color_manual(
    values = c(
      "estimate_tau2_rmse" = "#1f77b4",
      "naive_tau2_rmse" = "#ff7f0e"
    ),
    labels = c(
      "estimate_tau2_rmse" = "Meta-DiSCO estimate",
      "naive_tau2_rmse" = "Naive estimate"
    )) + 
  
  theme_minimal() + 
  theme_pubr()+ 
  theme_publication_text()

plot_tau2
# Optional: Display plots side by side
library(gridExtra)

p1 <- grid.arrange(plot_mu, plot_tau2, ncol = 2)
p2 <- grid.arrange(plot_mu, plot_tau, ncol = 2)
print(p1)

save_plots(plot = p1, directory = file.path(BASE_DIR, 
                                            "output/simulation/spatial_cox_process"),
           plot_name = "mu_v_tau2_rmse_plots",
           height = 3, 
           width=6.5)
save_plots(plot = p2, directory = file.path(BASE_DIR, 
                                            "output/simulation/spatial_cox_process"),
           plot_name = "mu_v_tau_rmse_plots",
           height = 3, 
           width=6.5)

```

```{r}
# Example graphics in pieces for how the cluster process is simulated
# Parameters 
set.seed(4)
parent_lambda0 <- rbeta(1, 2, 2) / WINDOW_SIZE
offspring_n0 <- rnbinom(1, size = 10, mu = 5) + 1
offspring_dispersion0 <- abs(rnorm(1, 0, 5))
Theta <- c(parent_lambda0, offspring_n0, offspring_dispersion0)


labels = c("A", "B", "C", "D")
plots <- list()
for(idx in 1:4) {
  set.seed(idx)
  parents <- rmpoispp(lambda = c(parent_lambda0, 0), win = square(WINDOW_SIZE), types=c("A", "B"))
  parent_spomic <- create_spomic(ppp_to_df(parents, sample_name = ""))
  
  parent_plot <- plot_spomic(parent_spomic, point_size = 0.5) + 
    labs(x = "x", y = "y") + 
    theme_pubr() + 
    theme_publication_text() + 
    theme(legend.title = element_blank()) 
  parent_plot
  
  offspring_x <- numeric()
  offspring_y <- numeric()
    
  if (parents$n > 0) {
    num_offspring <- rpois(parents$n, offspring_n0) + 1
    new_x <- rnorm(sum(num_offspring), 
                   mean = rep(parents$x, num_offspring), 
                   sd = offspring_dispersion0)
    new_y <- rnorm(sum(num_offspring), 
                   mean = rep(parents$y, num_offspring), 
                   sd = offspring_dispersion0)
      
    valid_idx <- (new_x >= 0) & (new_x <= WINDOW_SIZE) & (new_y >= 0) & (new_y <= WINDOW_SIZE)
    offspring_x <- new_x[valid_idx]
    offspring_y <- new_y[valid_idx]
    }
        
  parent_ppp <- ppp(parents$x, parents$y, window = square(WINDOW_SIZE), marks = rep("A", parents$n))
  offspring_ppp <- ppp(offspring_x, offspring_y, window = square(WINDOW_SIZE), marks = rep("B", length(offspring_x)))
  marked_process <- superimpose(parent_ppp, offspring_ppp)
  marks(marked_process) <- as.factor(marks(marked_process))
      
  family_spomic <- create_spomic(ppp_to_df(marked_process, sample_name = ""))
  
  family_plot <- plot_spomic(family_spomic, point_size = 0.5) + 
    labs(x = "x", y = "y") + 
    theme_pubr() + 
    theme_publication_text() + 
    theme(legend.title = element_blank()) 
  family_plot
  
  # plots[[idx]] <- plot_grid(parent_plot, family_plot, labels = c(labels[idx]))
    plots[[idx]] <- family_plot

}

intra_sample_plots <- plot_grid(plots[[1]], plots[[2]], plots[[3]], plots[[4]], labels = "B", nrow=1, 
  align = "hv",
  axis = "tblr",
  greedy = TRUE)



ggsave(filename = "/Users/jacobchang/Lab/metadisco_paper/figures/poster/intra_sample_cluster_process_example.pdf", 
       width = 6.5, height = 4, unit = "in")

```

```{r}
# Example graphics in pieces for how the cluster process is simulated
# Parameters 
# set.seed(4)
# parent_lambda0 <- rbeta(1, 2, 2) / WINDOW_SIZE
# offspring_n0 <- rnbinom(1, size = 10, mu = 5) + 1
# offspring_dispersion0 <- abs(rnorm(1, 0, 5))
# Theta <- c(parent_lambda0, offspring_n0, offspring_dispersion0)


labels = c("A", "B", "C", "D")
plots <- list()
for(idx in 1:10) {
  set.seed(idx)
parent_lambda0 <- rbeta(1, 2, 2) / WINDOW_SIZE
offspring_n0 <- rnbinom(1, size = 10, mu = 5) + 1
offspring_dispersion0 <- abs(rnorm(1, 0, 5))
Theta <- c(parent_lambda0, offspring_n0, offspring_dispersion0)
  parents <- rmpoispp(lambda = c(parent_lambda0, 0), win = square(WINDOW_SIZE), types=c("A", "B"))
  parent_spomic <- create_spomic(ppp_to_df(parents, sample_name = ""))
  
  parent_plot <- plot_spomic(parent_spomic, point_size = 0.5) + 
    labs(x = "x", y = "y") + 
    theme_pubr() + 
    theme_publication_text() + 
    theme(legend.title = element_blank()) 
  parent_plot
  
  offspring_x <- numeric()
  offspring_y <- numeric()
    
  if (parents$n > 0) {
    num_offspring <- rpois(parents$n, offspring_n0) + 1
    new_x <- rnorm(sum(num_offspring), 
                   mean = rep(parents$x, num_offspring), 
                   sd = offspring_dispersion0)
    new_y <- rnorm(sum(num_offspring), 
                   mean = rep(parents$y, num_offspring), 
                   sd = offspring_dispersion0)
      
    valid_idx <- (new_x >= 0) & (new_x <= WINDOW_SIZE) & (new_y >= 0) & (new_y <= WINDOW_SIZE)
    offspring_x <- new_x[valid_idx]
    offspring_y <- new_y[valid_idx]
    }
        
  parent_ppp <- ppp(parents$x, parents$y, window = square(WINDOW_SIZE), marks = rep("A", parents$n))
  offspring_ppp <- ppp(offspring_x, offspring_y, window = square(WINDOW_SIZE), marks = rep("B", length(offspring_x)))
  marked_process <- superimpose(parent_ppp, offspring_ppp)
  marks(marked_process) <- as.factor(marks(marked_process))
      
  family_spomic <- create_spomic(ppp_to_df(marked_process, sample_name = ""))
  
  family_plot <- plot_spomic(family_spomic, point_size = 0.5) + 
    labs(x = "x", y = "y") + 
    theme_pubr() + 
    theme_publication_text() + 
    theme(legend.title = element_blank()) 
  family_plot
  
  plots[[idx]] <- family_plot

  # plots[[idx]] <- plot_grid(parent_plot, family_plot, labels = c(labels[idx]))
}

inter_sample_plots <- plot_grid(plots[[1]], plots[[6]], plots[[7]], plots[[9]], labels = "A",  nrow=1, 
  align = "hv",
  axis = "tblr",
  greedy = TRUE)



ggsave(filename = "/Users/jacobchang/Lab/metadisco_paper/figures/poster/inter_sample_cluster_process_example.pdf", 
       width = 6.5, height = 4, unit = "in")

```

```{r}
total_plot <- plot_grid(
  inter_sample_plots, 
  intra_sample_plots, 
  nrow=2, 
    rel_heights = c(1, 1),
  align = "v",
  axis = "lr",
  greedy = TRUE
)
total_plot

ggsave(filename = "/Users/jacobchang/Lab/metadisco_paper/figures/poster/total_sample_cluster_process_example.pdf", 
       width = 10, height = 6, unit = "in")
```

